### ISSUE TITLE
DTE0024 not rendering related items

### ISSUE THREAD

**Issue by benjaminxscott** [MITRECND/mitrecnd.github.io#1]
Looks like [the DTE0024 page](https://shield.mitre.org/techniques/DTE0024/) doesn't render any related mappings for tactics/opportunities/etc 

Looks like [DTE0024 isn't listed as a mapping key in this file](https://github.com/MITRECND/mitrecnd.github.io/blob/master/_data/tactic_matrix.json) if that's related to this issue

**Comment by mgoffin** [comment]
Thank you very much for noticing! We have removed `DTE0024` for the time being. If you have any content you wish to contribute that is associated with that Technique, please contact us at shield@mitre.org!
